---
    -   hosts: 127.0.0.1
        connection: local
        become: yes
        remote_user: root
        vars:
             NOME_REDE_INTERNA_CONTAINER: 'embrapi'
             SUBREDE_INTERNA: '192.187.3.0/24'
             docker_apt_key: /etc/apt/keyrings/docker.gpg
             docker_repo: "deb [arch=amd64 signed-by={{ docker_apt_key }}] https://download.docker.com/linux/ubuntu mantic stable"
        tasks:
                        
            - name: Remover versões antigas do Docker
              apt:
                name: "{{ item }}"
                state: absent
                purge: yes
              loop:
                - docker
                - docker-engine
                - docker.io
                - containerd
                - runc

            - name: Instalar dependências necessárias
              apt:
                name:
                  - ca-certificates
                  - curl
                  - gnupg
                  - lsb-release
                state: present
                update_cache: true

            - name: Criar diretório para chave GPG do Docker
              file:
                path: /etc/apt/keyrings
                state: directory
                mode: '0755'

            - name: Adicionar chave GPG oficial do Docker
              ansible.builtin.get_url:
                url: https://download.docker.com/linux/ubuntu/gpg
                dest: "{{ docker_apt_key }}"
                mode: '0644'
              register: gpg_key
                        
            - name: Convert GPG key to dearmored format (if needed)
              shell: |
                gpg --dearmor < {{ docker_apt_key }} > {{ docker_apt_key }}.tmp && mv {{ docker_apt_key }}.tmp {{ docker_apt_key }}
              when: gpg_key.changed
           
            - name: Adicionar repositório do Docker
              apt_repository:
                repo: "{{ docker_repo }}"
                state: present
                filename: docker

            - name: Atualizar cache do APT
              apt:
                update_cache: true

            - name: Instalar Docker Engine e componentes
              apt:
                name:
                  - docker-ce
                  - docker-ce-cli
                  - containerd.io
                  - docker-buildx-plugin
                  - docker-compose-plugin
                state: present

            - name: Adicionar usuário atual ao grupo docker
              user:
                name: "{{ ansible_user }}"
                groups: docker
                append: yes

            - name: Garantir que o serviço Docker esteja iniciado e habilitado
              systemd:
                name: docker
                enabled: true
                state: started

            - name: Garantir que a rede interna do Docker exista
              community.docker.docker_network:
                name: "{{ NOME_REDE_INTERNA_CONTAINER }}"
                driver: bridge
                ipam_config:
                  - subnet: "{{ SUBREDE_INTERNA }}"
                state: present
